# Generated by Django 4.2 on 2024-11-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание блюда')),
                ('portion', models.CharField(blank=True, max_length=10, verbose_name='Порция')),
                ('price', models.IntegerField(max_length=10, verbose_name='Цена')),
            ],
        ),
    ]
