# Generated by Django 4.2 on 2024-11-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_site', '0003_alter_menu_options_alter_menu_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фотография')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe_site.menu', verbose_name='Объявление')),
            ],
        ),
    ]
