# Generated by Django 4.2 on 2024-12-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_site', '0004_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['price'], 'verbose_name': 'Салат', 'verbose_name_plural': 'Салаты'},
        ),
    ]
